name: Deploy Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '13.10'

      - name: Install dependencies
        run: npm install
        env:
          CI: true

      - name: Run tests
        run: npm test
        env:
          CI: true

      - name: Run linter
      run: npm run lint
      env:
        CI: true

      - name: Build project
        run: npm run build
        env:
          CI: true

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=dist --prod
